#ifndef knownglyphs_h
#define knownglyphs_h
#include "Glyph.h"

/*
                  k
       p                       n
            a            e
                  t
            o            i
       m                       b 
                  s


#define G_ "",""

*/
#define __EMPTY "x","x"
#define G_ABANDON "netoms","abandon"
#define G_ADAPT "itop","adapt"
#define G_ADVANCE "mak","advance"
#define G_AFTER "tenbit","after"
#define G_AGAIN "maotei","again"
#define G_ALL "bnkpmsb","all"
#define G_ANSWER "aeit","answer"
#define G_ATTACK "mkb","attack"
#define G_AVOID "pkeni","avoid"

#define G_BARRIER "ktib","barrier"
#define G_BEFORE "tompa","before"
#define G_BEGIN "isok","begin"
#define G_BEING "eisoae","being"
#define G_BODY "aeta","body"
#define G_BREATHE "ptn","breathe"
#define G_CAPTURE "smtin","capture"
#define G_CHANGE "otsi","change"
#define G_CHAOS "mpknos","chaos"

#define G_CLEAR "ks","clear"
#define G_CLEARALL "ksbnkpms","clearall"
#define G_COMPLEX "eato","complex"
#define G_CONFLICT "maoieb","conflict"
#define G_CONSEQUENCE "paoib","consequence"
#define G_CONTEMPLATE "etaosbnk","contemplate"
#define G_CONTRACT "ieb","contract"

#define G_COURAGE "maoi","courage"
#define G_CREATE "mn","create"
#define G_CREATIVITY "stams","creativity"
#define G_DESTINATION "sbn","destination"
#define G_DESTINY "ateios","destiny"
#define G_DESTROY "pb","destroy"
#define G_DESTRUCTION "pb","destruction"
#define G_DETERIORATE "mta","deteriorate"
#define G_DIE "mtb","die"
#define G_DIFFICULT "otien","difficult"
#define G_DISCOVER "msbn","discover"
#define G_DISTANCE "mpk","distance"
#define G_OUTSIDE "mpk","outside"
#define G_EASY "soe","easy"
#define G_END "skns","end"
#define G_CLOSE "skns","close"
#define G_FINALITY "skns","finality"
#define G_ENLIGHTENED "aetaknbs","enlightened"
#define G_ENLIGHTENMENT "aetaknbsm","enlightenment"
#define G_EQUAL "oaei","equal"
#define G_ESCAPE "oaenk","escape"
#define G_EVOLUTION "oatk","evolution"
#define G_SUCCESS "oatk","success"
#define G_PROGRESS "oatk","progress"
#define G_FAILURE "ietk","failure"
#define G_FEAR "aein","fear"
#define G_FOLLOW "kenb","follow"
#define G_FORGET "mo","forget"
#define G_FUTURE "bien","future"
#define G_GAIN "po","gain"
#define G_GOVERNMENT "paoien","government"
#define G_CIVILIZATION "paoien","civilization"
#define G_CITY "paoien","city"
#define G_STRUCTURE "paoien","structure"
#define G_GROW "mao","grow"
#define G_HARM "baket","harm"
#define G_HARMONY "keosiak","harmony"
#define G_PEACE "soekais","peace"
#define G_HAVE "soti","have"
#define G_HELP "ptoi","help"
#define G_HIDE "aenio","hide"
#define G_ME "saes","me"
#define G_SELF "aesa","self"
#define G_IGNORE "ib","ignore"
#define G_IMPERFECT "eoat","imperfect"
#define G_IMPROVE "itn","improve"
#define G_IMPURE "staot","impure"
#define G_INTERRUPT "ktmpts","interrupt"
#define G_JOURNEY "smptn","journey"
#define G_KNOWLEDGE "sates","knowledge"
#define G_LEAD "sompk","lead"
#define G_LEGACY "moapkneib","legacy"
#define G_LESS "ate","less"
#define G_LIBERATE "matnk","liberate"
#define G_LIE "oaiet","lie"
#define G_REINCARNATE "maon","reincarnate"
#define G_LOSS "in","loss"
#define G_MESSAGE "main","message"
#define G_MIND "taost","mind"
#define G_THOUGHT "taost","thought"
#define G_IDEA "taost","idea"
#define G_MORE "oti","more"
#define G_MYSTERY "oakeap","mystery"
#define G_NZEER "sketak","nzeer"
#define G_NATURE "moaeib","nature"
#define G_NEW "eib","new"
#define G_NO "aei","no"
#define G_NOT "aei","not"
#define G_ABSENT "aei","absent"
#define G_INSIDE "aei","inside"
#define G_NOURISH "mtsm","nourish"
#define G_OLD "pao","old"
#define G_OPEN "sois","open"
#define G_ACCEPT "oiso","accept"
#define G_OPENALL "soismpknbs","openall"
#define G_PORTAL "pmoibneap","portal"
#define G_PAST "paom","past"
#define G_PATH "mtk","path"
#define G_PERFECTION "ktmsbt","perfection"
#define G_BALANCE "ktbsmt","balance"
#define G_PERSPECTIVE "mekab","perspective"
#define G_POTENTIAL "ktbn","potential"
#define G_PRESENCE "oietaosi","presence"
#define G_PRESENT "aoie","present"
#define G_NOW "aoie","now"
#define G_PURE "kteit","pure"
#define G_PURITY "ktiet","purity"
#define G_PURSUE "pake","pursue"
#define G_CHASE "moatk","chase"
#define G_QUESTION "oaek","question"
#define G_REACT "eab","react"
#define G_REBEL "ponb","rebel"
#define G_RECHARGE "pktp","recharge"
#define G_RESIST "eaksi","resist"
#define G_RESTRAINT "sbp","restraint"
#define G_RETREAT "kb","retreat"
#define G_SAFETY "maeb","safety"
#define G_RESCUE "otin","rescue"
#define G_SAVE "nito","save"
#define G_SEE "ka","see"
#define G_SEARCH "teaoi","search"
#define G_SEEK "ioaet","seek"
#define G_SELF "msb","self"
#define G_SEPARATE "paoeib","separate"
#define G_SHAPER "moakeib","shaper"
#define G_COLLECTIVE "biekaom","collective"
#define G_SHARE "smoib","share"
#define G_SIMPLE "oi","simple"
#define G_SOUL "steis","soul"
#define G_SPIRIT "teist","spirit"
#define G_STABILITY "moib","stability"
#define G_STAY "biom","stay"
#define G_STRONG "aoiea","strong"
#define G_TOGETHER "meat","together"
#define G_TRUTH "aoeia","truth"
#define G_UNBOUNDED "teaoinkpmsb","unbounded"
#define G_USE "tin","use"
#define G_VICTORY "sakes","victory"
#define G_WANT "mosi","want"
#define G_DESIRE "isom","desire"
#define G_WE "aes","we"
#define G_US "sea","us"
#define G_WEAK "paei","weak"
#define G_WORTH "potin","worth"
#define G_XM "aeitoa","XM"
#define G_YOU "oiko","you"
#define G_OTHER "okio","other"
#define G_FROG "moakeibsm","frog"
#define G_DISORDER "mpknos","disorder"
#define G_ERODE "mta","erode"
#define G_HUMAN "eisoae","human"
#define G_OBSTACLE "ktib","obstacle"
#define G_REPEAT "maotei","repeat"
#define G_MODIFY "otsi","modify"
#define G_STRUGGLE "pkeni","struggle"
#define G_SHELL "aeta","shell"
#define G_WAR "mkb","war"
#define G_HUMAN "eisoae","human"
#define G_THINK "ompbne","think"
#define G_REDUCE "bei","reduce"
#define G_RESISTANCE "oskae","resistance"
#define G_LOSE "ni","lose"

#endif
